import Link from "next/link";

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-surface flex flex-col items-center py-20 px-4">
      <div className="max-w-3xl w-full">
        <Link href="/" className="inline-flex items-center gap-2 text-primary hover:-translate-x-1 transition-transform mb-8">
          <span className="material-symbols-outlined text-[20px]">arrow_back</span>
          <span className="font-medium text-[14px]">Back to Home</span>
        </Link>
        <h1 className="text-3xl md:text-4xl font-bold text-on-surface mb-8">Terms & Conditions</h1>
        
        <div className="space-y-10 text-[15px] text-on-surface-variant leading-relaxed">
          
          <div>
            <h2 className="text-[14px] font-bold text-primary uppercase tracking-wider mb-4 border-b border-outline-variant/30 pb-2">Service Terms</h2>
            <div className="space-y-6">
              <section>
                <h3 className="text-[18px] font-semibold text-on-surface mb-2">Not Legal Advice</h3>
                <p>
                  DocAudit AI uses artificial intelligence to identify potential risks and summarize documents. The output generated by this service is for informational purposes only and <strong className="text-on-surface">does not constitute legal advice</strong>. You should always consult with a qualified attorney for legal matters.
                </p>
              </section>
              <section>
                <h3 className="text-[18px] font-semibold text-on-surface mb-2">Service Limitations</h3>
                <p>
                  We provide this service "as is" without warranties. While we strive for high accuracy, AI can make mistakes. We are not liable for any damages or losses arising from your reliance on the analysis provided by our platform.
                </p>
              </section>
            </div>
          </div>

          <div>
            <h2 className="text-[14px] font-bold text-primary uppercase tracking-wider mb-4 border-b border-outline-variant/30 pb-2">Privacy & Data Handling</h2>
            <div className="space-y-6">
              <section>
                <h3 className="text-[18px] font-semibold text-on-surface mb-2">Document Storage & Deletion</h3>
                <p>
                  Your documents belong to you. Any file uploaded to DocAudit AI is encrypted in transit and at rest. We automatically and permanently delete all uploaded files and their associated analysis from our servers exactly 2 hours after upload.
                </p>
              </section>
              <section>
                <h3 className="text-[18px] font-semibold text-on-surface mb-2">No AI Training</h3>
                <p>
                  We do not use your documents to train, fine-tune, or improve our AI models. We utilize Google's Gemini AI API, governed by strict enterprise data privacy agreements that prohibit using the data for model training.
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
